//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winFrost {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Winfrost1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Winfrost1 defaultInstance = ((Winfrost1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Winfrost1())));
        
        public static Winfrost1 Default {
            get {
                return defaultInstance;
            }
        }
    }
}
